# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bilgi_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_bilgi(object):
    def setupUi(self, bilgi):
        bilgi.setObjectName("bilgi")
        bilgi.resize(640, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(bilgi.sizePolicy().hasHeightForWidth())
        bilgi.setSizePolicy(sizePolicy)
        bilgi.setMinimumSize(QtCore.QSize(640, 480))
        bilgi.setMaximumSize(QtCore.QSize(640, 480))
        bilgi.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/logos/birimcevirici.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        bilgi.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(bilgi)
        self.label.setGeometry(QtCore.QRect(100, 40, 441, 41))
        font = QtGui.QFont()
        font.setFamily("Formula1 Display Bold")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton_menuyedon_bilgi = QtWidgets.QPushButton(bilgi)
        self.pushButton_menuyedon_bilgi.setGeometry(QtCore.QRect(560, 400, 50, 50))
        self.pushButton_menuyedon_bilgi.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButton_menuyedon_bilgi.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton_menuyedon_bilgi.setStyleSheet("background-image: url(src/logos/exit2.png);")
        self.pushButton_menuyedon_bilgi.setText("")
        self.pushButton_menuyedon_bilgi.setObjectName("pushButton_menuyedon_bilgi")
        self.label_menuyedon_3 = QtWidgets.QLabel(bilgi)
        self.label_menuyedon_3.setGeometry(QtCore.QRect(550, 450, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Formula1")
        font.setPointSize(6)
        self.label_menuyedon_3.setFont(font)
        self.label_menuyedon_3.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_menuyedon_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_menuyedon_3.setObjectName("label_menuyedon_3")
        self.pushButton_iuc = QtWidgets.QPushButton(bilgi)
        self.pushButton_iuc.setGeometry(QtCore.QRect(230, 430, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_iuc.sizePolicy().hasHeightForWidth())
        self.pushButton_iuc.setSizePolicy(sizePolicy)
        self.pushButton_iuc.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton_iuc.setStyleSheet("QPushButton {\n"
"\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background-image: url(src/logos/iuc.png);\n"
"    padding: 5px;\n"
"    }\n"
"")
        self.pushButton_iuc.setText("")
        self.pushButton_iuc.setObjectName("pushButton_iuc")
        self.pushButton_github = QtWidgets.QPushButton(bilgi)
        self.pushButton_github.setGeometry(QtCore.QRect(300, 430, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_github.sizePolicy().hasHeightForWidth())
        self.pushButton_github.setSizePolicy(sizePolicy)
        self.pushButton_github.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton_github.setStyleSheet("QPushButton {\n"
"\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background-image: url(src/logos/github.png);\n"
"    padding: 5px;\n"
"    }\n"
"    ")
        self.pushButton_github.setText("")
        self.pushButton_github.setObjectName("pushButton_github")
        self.pushButton_tbmyo = QtWidgets.QPushButton(bilgi)
        self.pushButton_tbmyo.setGeometry(QtCore.QRect(370, 429, 41, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_tbmyo.sizePolicy().hasHeightForWidth())
        self.pushButton_tbmyo.setSizePolicy(sizePolicy)
        self.pushButton_tbmyo.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton_tbmyo.setStyleSheet("QPushButton {\n"
"\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background-image: url(src/logos/tbmyo.png);\n"
"    padding: 5px;\n"
"    }\n"
"")
        self.pushButton_tbmyo.setText("")
        self.pushButton_tbmyo.setObjectName("pushButton_tbmyo")
        self.label_2 = QtWidgets.QLabel(bilgi)
        self.label_2.setGeometry(QtCore.QRect(10, 120, 621, 301))
        font = QtGui.QFont()
        font.setFamily("Formula1")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(bilgi)
        QtCore.QMetaObject.connectSlotsByName(bilgi)

    def retranslateUi(self, bilgi):
        _translate = QtCore.QCoreApplication.translate
        bilgi.setWindowTitle(_translate("bilgi", "Birim Çevirici - Bilgi"))
        self.label.setText(_translate("bilgi", "Bilgi Menüsü"))
        self.label_menuyedon_3.setText(_translate("bilgi", "MENÜYE DÖN"))
        self.label_2.setText(_translate("bilgi", "<html><head/><body><p>Bu uygulama, İÜC Elektronik Teknolojisi öğrencileri; Turan Özkan Temuralay, Eray Öztürk ve Burak Aydın tarafından Proje (ELTE2087) dersi için hazırlanmıştır.<br/></p><p>Bu proje, elektronik ağırlıklı olmak üzere çeşitli birimlerin dönüşümlerini yapmayı amaçlamaktadır.<br/></p><p>Proje; Python programlama dilinde, PyQT5 kütüphanesi kullanalıarak hazırlanmıştır. Arayüz, QT Designer aracılığıyla &quot;sürükle-bırak&quot; yöntemi kullanılarak hazırlanmıştır.<br/></p><p>Üniversitemizin ve bölümümüzün web-sitesi ve projenin tüm kaynak kodlarının bulunduğu github linki aşağıda verilmiştir.</p><p><br/></p><p>Keyifli kullanımlar dileriz!</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    bilgi = QtWidgets.QDialog()
    ui = Ui_bilgi()
    ui.setupUi(bilgi)
    bilgi.show()
    sys.exit(app.exec_())
