# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'binary_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_binary(object):
    def setupUi(self, binary):
        binary.setObjectName("binary")
        binary.resize(640, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(binary.sizePolicy().hasHeightForWidth())
        binary.setSizePolicy(sizePolicy)
        binary.setMinimumSize(QtCore.QSize(640, 480))
        binary.setMaximumSize(QtCore.QSize(640, 480))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/logos/birimcevirici.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        binary.setWindowIcon(icon)
        self.groupBox_binary = QtWidgets.QGroupBox(binary)
        self.groupBox_binary.setGeometry(QtCore.QRect(80, 40, 471, 361))
        font = QtGui.QFont()
        font.setFamily("Formula1")
        font.setPointSize(14)
        self.groupBox_binary.setFont(font)
        self.groupBox_binary.setObjectName("groupBox_binary")
        self.comboBox_giris_binary = QtWidgets.QComboBox(self.groupBox_binary)
        self.comboBox_giris_binary.setGeometry(QtCore.QRect(30, 180, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_giris_binary.setFont(font)
        self.comboBox_giris_binary.setObjectName("comboBox_giris_binary")
        self.comboBox_giris_binary.addItem("")
        self.comboBox_giris_binary.addItem("")
        self.comboBox_giris_binary.addItem("")
        self.comboBox_giris_binary.addItem("")
        self.lineEdit_giris_binary = QtWidgets.QLineEdit(self.groupBox_binary)
        self.lineEdit_giris_binary.setGeometry(QtCore.QRect(40, 140, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_giris_binary.setFont(font)
        self.lineEdit_giris_binary.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_giris_binary.setObjectName("lineEdit_giris_binary")
        self.label_cikis_binary = QtWidgets.QLabel(self.groupBox_binary)
        self.label_cikis_binary.setGeometry(QtCore.QRect(320, 110, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_cikis_binary.setFont(font)
        self.label_cikis_binary.setObjectName("label_cikis_binary")
        self.label_giris_binary = QtWidgets.QLabel(self.groupBox_binary)
        self.label_giris_binary.setGeometry(QtCore.QRect(40, 110, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_giris_binary.setFont(font)
        self.label_giris_binary.setAlignment(QtCore.Qt.AlignCenter)
        self.label_giris_binary.setObjectName("label_giris_binary")
        self.lineEdit_cikis_binary = QtWidgets.QLineEdit(self.groupBox_binary)
        self.lineEdit_cikis_binary.setGeometry(QtCore.QRect(300, 140, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_cikis_binary.setFont(font)
        self.lineEdit_cikis_binary.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_cikis_binary.setObjectName("lineEdit_cikis_binary")
        self.comboBox_cikis_binary = QtWidgets.QComboBox(self.groupBox_binary)
        self.comboBox_cikis_binary.setGeometry(QtCore.QRect(290, 180, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_cikis_binary.setFont(font)
        self.comboBox_cikis_binary.setObjectName("comboBox_cikis_binary")
        self.comboBox_cikis_binary.addItem("")
        self.comboBox_cikis_binary.addItem("")
        self.comboBox_cikis_binary.addItem("")
        self.comboBox_cikis_binary.addItem("")
        self.pushButton_menuyedon_binary = QtWidgets.QPushButton(binary)
        self.pushButton_menuyedon_binary.setGeometry(QtCore.QRect(560, 390, 50, 50))
        self.pushButton_menuyedon_binary.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButton_menuyedon_binary.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton_menuyedon_binary.setStyleSheet("background-image: url(src/logos/exit2.png);")
        self.pushButton_menuyedon_binary.setText("")
        self.pushButton_menuyedon_binary.setObjectName("pushButton_menuyedon_binary")
        self.label_menuyedon_kutle = QtWidgets.QLabel(binary)
        self.label_menuyedon_kutle.setGeometry(QtCore.QRect(550, 440, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Formula1")
        font.setPointSize(6)
        self.label_menuyedon_kutle.setFont(font)
        self.label_menuyedon_kutle.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_menuyedon_kutle.setAlignment(QtCore.Qt.AlignCenter)
        self.label_menuyedon_kutle.setObjectName("label_menuyedon_kutle")
        self.pushButton_bilgi = QtWidgets.QPushButton(binary)
        self.pushButton_bilgi.setGeometry(QtCore.QRect(10, 450, 20, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_bilgi.sizePolicy().hasHeightForWidth())
        self.pushButton_bilgi.setSizePolicy(sizePolicy)
        self.pushButton_bilgi.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton_bilgi.setStyleSheet("QPushButton {\n"
"\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background-image: url(src/logos/info2.png);\n"
"    padding: 5px;\n"
"    }\n"
"    ")
        self.pushButton_bilgi.setText("")
        self.pushButton_bilgi.setObjectName("pushButton_bilgi")

        self.retranslateUi(binary)
        QtCore.QMetaObject.connectSlotsByName(binary)

    def retranslateUi(self, binary):
        _translate = QtCore.QCoreApplication.translate
        binary.setWindowTitle(_translate("binary", "Birim Çevirici - Binary"))
        self.groupBox_binary.setTitle(_translate("binary", "Binary Çevirme Menüsü"))
        self.comboBox_giris_binary.setItemText(0, _translate("binary", "decimal"))
        self.comboBox_giris_binary.setItemText(1, _translate("binary", "binary"))
        self.comboBox_giris_binary.setItemText(2, _translate("binary", "octal"))
        self.comboBox_giris_binary.setItemText(3, _translate("binary", "hexadecimal"))
        self.label_cikis_binary.setText(_translate("binary", "Çıkış Değeri"))
        self.label_giris_binary.setText(_translate("binary", "Giriş Değeri"))
        self.comboBox_cikis_binary.setItemText(0, _translate("binary", "decimal"))
        self.comboBox_cikis_binary.setItemText(1, _translate("binary", "binary"))
        self.comboBox_cikis_binary.setItemText(2, _translate("binary", "octal"))
        self.comboBox_cikis_binary.setItemText(3, _translate("binary", "hexadecimal"))
        self.label_menuyedon_kutle.setText(_translate("binary", "MENÜYE DÖN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    binary = QtWidgets.QDialog()
    ui = Ui_binary()
    ui.setupUi(binary)
    binary.show()
    sys.exit(app.exec_())
