# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ohmkurali_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ohm(object):
    def setupUi(self, ohm):
        ohm.setObjectName("ohm")
        ohm.resize(640, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ohm.sizePolicy().hasHeightForWidth())
        ohm.setSizePolicy(sizePolicy)
        ohm.setMinimumSize(QtCore.QSize(640, 480))
        ohm.setMaximumSize(QtCore.QSize(640, 480))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/logos/birimcevirici.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ohm.setWindowIcon(icon)
        self.label_menuyedon_kutle = QtWidgets.QLabel(ohm)
        self.label_menuyedon_kutle.setGeometry(QtCore.QRect(550, 440, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Formula1")
        font.setPointSize(6)
        self.label_menuyedon_kutle.setFont(font)
        self.label_menuyedon_kutle.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_menuyedon_kutle.setAlignment(QtCore.Qt.AlignCenter)
        self.label_menuyedon_kutle.setObjectName("label_menuyedon_kutle")
        self.groupBox_ohm = QtWidgets.QGroupBox(ohm)
        self.groupBox_ohm.setGeometry(QtCore.QRect(80, 40, 471, 361))
        font = QtGui.QFont()
        font.setFamily("Formula1")
        font.setPointSize(14)
        self.groupBox_ohm.setFont(font)
        self.groupBox_ohm.setObjectName("groupBox_ohm")
        self.pushButton_hesapla_binary = QtWidgets.QPushButton(self.groupBox_ohm)
        self.pushButton_hesapla_binary.setGeometry(QtCore.QRect(160, 210, 151, 51))
        self.pushButton_hesapla_binary.setObjectName("pushButton_hesapla_binary")
        self.lineEdit_volt = QtWidgets.QLineEdit(self.groupBox_ohm)
        self.lineEdit_volt.setGeometry(QtCore.QRect(20, 130, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_volt.setFont(font)
        self.lineEdit_volt.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_volt.setObjectName("lineEdit_volt")
        self.label_amper = QtWidgets.QLabel(self.groupBox_ohm)
        self.label_amper.setGeometry(QtCore.QRect(190, 110, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_amper.setFont(font)
        self.label_amper.setAlignment(QtCore.Qt.AlignCenter)
        self.label_amper.setObjectName("label_amper")
        self.label_volt = QtWidgets.QLabel(self.groupBox_ohm)
        self.label_volt.setGeometry(QtCore.QRect(20, 110, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_volt.setFont(font)
        self.label_volt.setAlignment(QtCore.Qt.AlignCenter)
        self.label_volt.setObjectName("label_volt")
        self.lineEdit_ohm = QtWidgets.QLineEdit(self.groupBox_ohm)
        self.lineEdit_ohm.setGeometry(QtCore.QRect(320, 130, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_ohm.setFont(font)
        self.lineEdit_ohm.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_ohm.setObjectName("lineEdit_ohm")
        self.lineEdit_amper = QtWidgets.QLineEdit(self.groupBox_ohm)
        self.lineEdit_amper.setGeometry(QtCore.QRect(170, 130, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_amper.setFont(font)
        self.lineEdit_amper.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_amper.setObjectName("lineEdit_amper")
        self.label_ohm = QtWidgets.QLabel(self.groupBox_ohm)
        self.label_ohm.setGeometry(QtCore.QRect(340, 110, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_ohm.setFont(font)
        self.label_ohm.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ohm.setObjectName("label_ohm")
        self.pushButton_menuyedon_binary = QtWidgets.QPushButton(ohm)
        self.pushButton_menuyedon_binary.setGeometry(QtCore.QRect(560, 390, 50, 50))
        self.pushButton_menuyedon_binary.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButton_menuyedon_binary.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton_menuyedon_binary.setStyleSheet("background-image: url(src/logos/exit2.png);")
        self.pushButton_menuyedon_binary.setText("")
        self.pushButton_menuyedon_binary.setObjectName("pushButton_menuyedon_binary")
        self.pushButton_bilgi = QtWidgets.QPushButton(ohm)
        self.pushButton_bilgi.setGeometry(QtCore.QRect(10, 450, 20, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_bilgi.sizePolicy().hasHeightForWidth())
        self.pushButton_bilgi.setSizePolicy(sizePolicy)
        self.pushButton_bilgi.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton_bilgi.setStyleSheet("QPushButton {\n"
"\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background-image: url(src/logos/info2.png);\n"
"    padding: 5px;\n"
"    }\n"
"    ")
        self.pushButton_bilgi.setText("")
        self.pushButton_bilgi.setObjectName("pushButton_bilgi")

        self.retranslateUi(ohm)
        QtCore.QMetaObject.connectSlotsByName(ohm)

    def retranslateUi(self, ohm):
        _translate = QtCore.QCoreApplication.translate
        ohm.setWindowTitle(_translate("ohm", "Birim Çevirici - Ohm Kuralı"))
        self.label_menuyedon_kutle.setText(_translate("ohm", "MENÜYE DÖN"))
        self.groupBox_ohm.setTitle(_translate("ohm", "Ohm Kuralı Menüsü"))
        self.pushButton_hesapla_binary.setText(_translate("ohm", "HESAPLA"))
        self.label_amper.setText(_translate("ohm", "Akım (I)"))
        self.label_volt.setText(_translate("ohm", "Gerilim (V)"))
        self.label_ohm.setText(_translate("ohm", "Direnç (R)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ohm = QtWidgets.QDialog()
    ui = Ui_ohm()
    ui.setupUi(ohm)
    ohm.show()
    sys.exit(app.exec_())
